In [1]:
# how to load dataset of csv file
import pandas as pd

In [2]:
# Load the dataset from a CSV file
df = pd.read_csv("CleanedDataset_kideney.csv")

In [3]:

# Print the first five rows of the dataset
df.head()

,Age (yrs),Blood Pressure (mm/Hg),Specific Gravity,Albumin,Sugar,Blood Glucose Random (mgs/dL),Blood Urea (mgs/dL),Serum Creatinine (mgs/dL),Sodium (mEq/L),Potassium (mEq/L),...,Pus Cells: normal,Pus Cell Clumps: present,Bacteria: present,Hypertension: yes,Diabetes Mellitus: yes,Coronary Artery Disease: yes,Appetite: poor,Pedal Edema: yes,Anemia: yes,Chronic Kidney Disease: yes
0,48.0,80.0,1.020,1.0,0.0,121.000000,36.0,1.2,136.0,4.7,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1,7.0,50.0,1.020,4.0,0.0,90.316581,18.0,0.8,140.0,4.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,62.0,80.0,1.010,2.0,3.0,423.000000,53.0,1.8,135.0,4.8,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0
3,48.0,70.0,1.005,4.0,0.0,117.000000,56.0,3.8,111.0,2.5,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
4,51.0,80.0,1.010,2.0,0.0,106.000000,26.0,1.4,140.0,4.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
df.describe()

,Age (yrs),Blood Pressure (mm/Hg),Specific Gravity,Albumin,Sugar,Blood Glucose Random (mgs/dL),Blood Urea (mgs/dL),Serum Creatinine (mgs/dL),Sodium (mEq/L),Potassium (mEq/L),...,Pus Cells: normal,Pus Cell Clumps: present,Bacteria: present,Hypertension: yes,Diabetes Mellitus: yes,Coronary Artery Disease: yes,Appetite: poor,Pedal Edema: yes,Anemia: yes,Chronic Kidney Disease: yes
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,...,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,51.591123,76.300000,1.017449,0.935797,0.395000,146.005923,56.806872,3.022922,137.387860,4.569293,...,0.800000,0.105000,0.055000,0.367500,0.34250,0.085000,0.205000,0.190000,0.150000,0.625000
std,17.042814,13.593084,0.005597,1.311653,1.040038,76.422249,49.808436,5.631037,9.273123,2.829638,...,0.400501,0.306937,0.228266,0.482728,0.47514,0.279231,0.404207,0.392792,0.357519,0.484729
min,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,42.000000,70.000000,1.015000,0.000000,0.000000,100.000000,27.000000,0.900000,135.000000,3.900000,...,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,55.000000,80.000000,1.020000,0.000000,0.000000,119.491153,41.000000,1.300000,138.000000,4.400000,...,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,65.000000,80.000000,1.020000,2.000000,0.000000,159.250000,65.250000,2.800000,141.000000,4.900000,...,1.000000,0.000000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000
max,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age (yrs)                       400 non-null    float64
 1   Blood Pressure (mm/Hg)          400 non-null    float64
 2   Specific Gravity                400 non-null    float64
 3   Albumin                         400 non-null    float64
 4   Sugar                           400 non-null    float64
 5   Blood Glucose Random (mgs/dL)   400 non-null    float64
 6   Blood Urea (mgs/dL)             400 non-null    float64
 7   Serum Creatinine (mgs/dL)       400 non-null    float64
 8   Sodium (mEq/L)                  400 non-null    float64
 9   Potassium (mEq/L)               400 non-null    float64
 10  Hemoglobin (gms)                400 non-null    float64
 11  Packed Cell Volume              400 non-null    float64
 12  White Blood Cells (cells/cmm)   400 non-null    float64
 13  Red Blood Cells (millions/cmm)  400 non-null    float64
 14  Red Blood Cells: normal         400 non-null    float64
 15  Pus Cells: normal               400 non-null    float64
 16  Pus Cell Clumps: present        400 non-null    float64
 17  Bacteria: present               400 non-null    float64
 18  Hypertension: yes               400 non-null    float64
 19  Diabetes Mellitus: yes          400 non-null    float64
 20  Coronary Artery Disease: yes    400 non-null    float64
 21  Appetite: poor                  400 non-null    float64
 22  Pedal Edema: yes                400 non-null    float64
 23  Anemia: yes                     400 non-null    float64
 24  Chronic Kidney Disease: yes     400 non-null    float64
dtypes: float64(25)
memory usage: 78.3 KB

In [20]:

# displaying the datatypes
display(df.dtypes)
 
# converting 'Weight' and 'Salary' from float to int
df = df.astype({"Age (yrs)": 'int', "Blood Pressure (mm/Hg)": 'int',"Albumin":'int',"Sugar":'int',"Blood Glucose Random (mgs/dL)":'int',
               "Blood Urea (mgs/dL)":'int', "Sodium (mEq/L)":'int',"Potassium (mEq/L)":'int',"Packed Cell Volume":'int',"White Blood Cells (cells/cmm)":'int',
                "Red Blood Cells: normal":'int',"Pus Cells: normal":'int',"Pus Cell Clumps: present":'int',"Bacteria: present":'int',"Hypertension: yes":'int',"Diabetes Mellitus: yes":'int',
                "Coronary Artery Disease: yes":'int',"Appetite: poor":'int',"Pedal Edema: yes":'int',"Anemia: yes":'int',"Chronic Kidney Disease: yes":'int'})
 
# displaying the datatypes
display(df.dtypes)

Age (yrs)                           int32
Blood Pressure (mm/Hg)              int32
Specific Gravity                  float64
Albumin                             int32
Sugar                               int32
Blood Glucose Random (mgs/dL)       int32
Blood Urea (mgs/dL)                 int32
Serum Creatinine (mgs/dL)         float64
Sodium (mEq/L)                      int32
Potassium (mEq/L)                   int32
Hemoglobin (gms)                  float64
Packed Cell Volume                  int32
White Blood Cells (cells/cmm)       int32
Red Blood Cells (millions/cmm)    float64
Red Blood Cells: normal             int32
Pus Cells: normal                   int32
Pus Cell Clumps: present            int32
Bacteria: present                   int32
Hypertension: yes                   int32
Diabetes Mellitus: yes              int32
Coronary Artery Disease: yes        int32
Appetite: poor                      int32
Pedal Edema: yes                    int32
Anemia: yes                         int32
Chronic Kidney Disease: yes       float64
dtype: object

Age (yrs)                           int32
Blood Pressure (mm/Hg)              int32
Specific Gravity                  float64
Albumin                             int32
Sugar                               int32
Blood Glucose Random (mgs/dL)       int32
Blood Urea (mgs/dL)                 int32
Serum Creatinine (mgs/dL)         float64
Sodium (mEq/L)                      int32
Potassium (mEq/L)                   int32
Hemoglobin (gms)                  float64
Packed Cell Volume                  int32
White Blood Cells (cells/cmm)       int32
Red Blood Cells (millions/cmm)    float64
Red Blood Cells: normal             int32
Pus Cells: normal                   int32
Pus Cell Clumps: present            int32
Bacteria: present                   int32
Hypertension: yes                   int32
Diabetes Mellitus: yes              int32
Coronary Artery Disease: yes        int32
Appetite: poor                      int32
Pedal Edema: yes                    int32
Anemia: yes                         int32
Chronic Kidney Disease: yes         int32
dtype: object

In [21]:
df.head()

,Age (yrs),Blood Pressure (mm/Hg),Specific Gravity,Albumin,Sugar,Blood Glucose Random (mgs/dL),Blood Urea (mgs/dL),Serum Creatinine (mgs/dL),Sodium (mEq/L),Potassium (mEq/L),...,Pus Cells: normal,Pus Cell Clumps: present,Bacteria: present,Hypertension: yes,Diabetes Mellitus: yes,Coronary Artery Disease: yes,Appetite: poor,Pedal Edema: yes,Anemia: yes,Chronic Kidney Disease: yes
0,48,80,1.020,1,0,121,36,1.2,136,4,...,1,0,0,1,1,0,0,0,0,1
1,6,50,1.020,4,0,90,18,0.8,140,4,...,1,0,0,0,0,0,0,0,0,1
2,62,80,1.010,2,3,423,53,1.8,135,4,...,1,0,0,0,1,0,1,0,1,1
3,48,70,1.005,4,0,117,56,3.8,111,2,...,0,1,0,1,0,0,1,1,1,1
4,51,80,1.010,2,0,106,26,1.4,140,4,...,1,0,0,0,0,0,0,0,0,1